### PR TITLE
Move to GitHub Pages

### LINKED ISSUE #3: Switch to GitHub Pages, Surge, or Netlify
This puppy is running on Heroku, and I pay $7/month for it. It doesn't have to be that way.

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #3 

I was going to set up travis and parcel for a quick deployment, but I realized that this doesn't really need any build. It's two files and 100 lines, last updated 3 years ago.

You can merge this and just enable GitHub Pages in the repo settings (+ force HTTPS) and you're done.

Also I run the PNGs through an optimizer and added title/description in the HTML

Preview: https://cdn.staticaly.com/gh/bfred-it/npmhub.org/patch-1/index.html

### CODE REVIEW

**Comment by bfred-it** [comment]
Yes, if your DNS provider has CNAME flattening (like CloudFlare) you can just set `npmhub.github.io `

otherwise you'll have to set these IP addresses for the root:

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

https://help.github.com/articles/setting-up-a-www-subdomain/
https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by zeke** [comment]
Looking into it: https://twitter.com/zeke/status/1075571131829051392

Would an ALIAS record to `npmhub.github.io` work?

I have enabled GitHub Pages on the master branch. Should http://npmhub.github.io/ be working now?

**Comment by bfred-it** [comment]
`npmhub.github.io` only works when you have a `npmhub.github.io` repo in the `npmhub` organization.

Only `npmhub.org` will work once you point the DNS to it.

Until then, `https://npmhub.github.io/npmhub.org` will work (except it redirects to the domain defined in the `CNAME` file)

**Comment by zeke** [comment]
screen shot 2018-12-20 at 8 56 11 am

I'll check back on it tomorrow.

**Pull request merged**
